"""
Mubashir - US15: Named constants for all strategy parameters.
Replaces all magic numbers across strategy files with descriptive names.
"""

# ===== Common Signal Thresholds =====
SIGNAL_BUY_THRESHOLD = 0.2
SIGNAL_SELL_THRESHOLD = -0.2

# ===== Momentum Strategy =====
MOMENTUM_MIN_PERIODS = 60
MOMENTUM_ROC_SHORT_WINDOW = 20
MOMENTUM_ROC_LONG_WINDOW = 60
MOMENTUM_ABS_MULTIPLIER = 2.0
MOMENTUM_ROC_SHORT_WEIGHT = 3
MOMENTUM_ROC_LONG_WEIGHT = 2
MOMENTUM_ROC_DIVISOR = 5
MOMENTUM_REL_MULTIPLIER = 3.0
MOMENTUM_WEIGHT_ABS = 0.4
MOMENTUM_WEIGHT_ROC = 0.3
MOMENTUM_WEIGHT_REL = 0.3

# ===== Mean Reversion Strategy =====
MEAN_REV_MIN_PERIODS = 30
MEAN_REV_STD_WINDOW = 20
MEAN_REV_MEAN_LOOKBACK = 50
MEAN_REV_ZSCORE_DIVISOR = 2.5
MEAN_REV_BOLLINGER_STD = 2
MEAN_REV_RSI_PERIOD = 14
MEAN_REV_RSI_CENTER = 50.0
MEAN_REV_RSI_SCALE = 20.0
MEAN_REV_WEIGHT_ZSCORE = 0.50
MEAN_REV_WEIGHT_BOLLINGER = 0.30
MEAN_REV_WEIGHT_RSI = 0.20
MEAN_REV_WEIGHT_ZSCORE_NO_RSI = 0.60
MEAN_REV_WEIGHT_BOLLINGER_NO_RSI = 0.40
MEAN_REV_ZONE_OVERSOLD = -2.0
MEAN_REV_ZONE_OVERBOUGHT = 2.0
MEAN_REV_ZONE_NEUTRAL = 0.5

# ===== Monte Carlo Strategy =====
MC_NUM_SIMULATIONS = 1000
MC_FORECAST_DAYS = 30
MC_MIN_PERIODS = 60
MC_VAR_WEIGHT = 0.4
MC_CVAR_WEIGHT = 0.6
MC_RISK_THRESHOLD = 0.10
MC_RISK_MULTIPLIER = 2.0
MC_PROB_SCALE = 4.0

# ===== Factor Model Strategy =====
FACTOR_MIN_PERIODS = 60
FACTOR_ROE_CENTER = 0.10
FACTOR_ROE_SCALE = 5.0
FACTOR_MARGIN_CENTER = 0.05
FACTOR_MARGIN_SCALE = 5.0
FACTOR_VOL_NORMALIZATION = 0.25
FACTOR_SIZE_CENTER = 10.0
FACTOR_SIZE_SCALE = 0.5
FACTOR_WEIGHT_VALUE = 0.25
FACTOR_WEIGHT_GROWTH = 0.15
FACTOR_WEIGHT_QUALITY = 0.25
FACTOR_WEIGHT_VOLATILITY = 0.20
FACTOR_WEIGHT_SIZE = 0.15

# ===== Signal Aggregator =====
STRATEGY_WEIGHTS = {
    "momentum": 0.30,
    "mean_reversion": 0.25,
    "monte_carlo": 0.25,
    "factor_model": 0.20,
}
AGG_BUY_THRESHOLD = 0.15
AGG_SELL_THRESHOLD = -0.15
AGG_BASE_CONFIDENCE_OFFSET = 40
AGG_AGREEMENT_BONUS_MAX = 10
AGG_COVERAGE_PENALTY_MAX = 15
AGG_CONFIDENCE_MAX = 100
AGG_CONFIDENCE_MIN = 30
